from apps.common.exceptions import CustomException


class UserConflictErr(CustomException):
    pass
